### PR TITLE
V1 doc updates for ruby

### PR DESCRIPTION
**Pull request by jpvajda**

### CODE REVIEW

**Comment by jpvajda** [comment]
@ppg pinging for PR review.

**Comment by jpvajda** [comment]
So we have some other V1 changes coming down the pipe in # that will require an SDK update but we seemed to be back up on this one. What would you like me to do? @ppg @run-o #2609? Update this this branch? or make a new one?

**Comment by ppg** [comment]
I'd say update this branch

**Comment by jpvajda** [comment]
@ppg  will so. I assume the same answer applies to my question on https://github.com/TheJumpCloud/jcapi-python/pull/9#issuecomment-386462948

**Comment by jpvajda** [comment]
@ppg @run-o  Ok this one I got right. the changes for the SI-1.9.1 release have been added to this PR.

**Comment by jpvajda** [comment]
Closing without merging as the SDK is outdated and starting with a fresh code gen  off the most current YAML seems like the logical way to go.

**Pull request closed without merging**
