### PR TITLE
RUBY-SDK-V1-Updates-7.31.18

### PR DESCRIPTION
**Pull request by jpvajda**
Includes:

New Get Organization endpoint
Multi-Tenant x-org-id documentation and functionality.
Corrections to to Command Endpoint Documentation
Remove ssh_keys from systemuserpost model

### CODE REVIEW

**Comment by jpvajda** [comment]
@adducci @ppg I'm Not sure why this update created conflicts in this SDK version. Probably could use some help in determining what the resolution is here.

**Comment by adducci** [comment]
I am also unsure why it created all these conflicts... hopefully in most cases the resolve will be to just accept the branch's changes.

**Comment by jpvajda** [comment]
@adducci what's the easiest way to accept the branch changes? I can regen the code, it's not that difficult, but I'm curious if I can just pull those diffs in using this existing PR.

**Comment by adducci** [comment]
You can do it from right from github by following the [resolve conflicts link](https://github.com/TheJumpCloud/jcapi-ruby/pull/8/conflicts) and for every conflict deleting the `master` section, leaving the branch section. 

Or you can do the merge locally (`git checkout master`, `git pull`, `git checkout <branch>`, `git merge master`) and then resolve the conflicts in your text editor and commit the changes. Depending on what text editor you use it may be easier/ harder to resolve conflicts this way. I use Visual Studio Code and find it more intuitive than github.

**Comment by jpvajda** [comment]
@adducci @ppg  I fixed the merge conflicts. Is this ok to merge this PR in now?

**Comment by adducci** [comment]
Before merging just have the one comment on this PR and the same question from the Java PR applies here, too https://github.com/TheJumpCloud/jcapi-java/pull/4#discussion_r207618209

**Comment by jpvajda** [comment]
Going to kill this PR and start with a fresh code-gen to resolve these conflicts.

**Pull request closed without merging**
